services:
    postgresql:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin_container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - postgresql
    growin.api:
        image: ${DOCKER_REGISTRY-}growinapi
        build:
            context: .
            dockerfile: Growin.Api/Dockerfile
        environment:
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        depends_on:
            - postgresql